name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      
      working-directory: ./NodeServer
      

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
    
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - run: npm ci
      working-directory: ${{env.working-directory}}
    - run: npm run build --if-present
      working-directory: ${{env.working-directory}}
    - run: npm test
      working-directory: ${{env.working-directory}}
